import React, { useEffect, useMemo, useState } from 'react';
import { getInspection, loadPack } from '../db.js';
import { isApplicable, scoreInspection } from '@shared/rules.mjs';

/**
 * PROVISIONAL INSPECTION RECEIPT
 *
 * Issued to the Master on the device, at the vessel, the moment both parties
 * have signed. It exists because of a hard constraint: the MCI number is a
 * unique incrementing reference allocated by the SERVER. Two devices working
 * offline cannot both allocate one without colliding, so no MCI number can be
 * issued at the vessel.
 *
 * The paper process has the same shape — the officer's carbon copy is handed
 * over at once, and the filed report follows. This receipt is the carbon copy:
 * it carries the findings, the deficiencies, both signatures and the time, and
 * it states plainly on its face that it is provisional and carries no MCI
 * number. The definitive MCI report is generated by the server after
 * synchronisation and supervisory approval, and reaches the agent through the
 * portal.
 */
export default function Receipt({ localId, go }) {
  const [insp, setInsp] = useState(null);
  const [pack, setPack] = useState(null);

  useEffect(() => {
    getInspection(localId).then(setInsp);
    loadPack().then(setPack);
  }, [localId]);

  const evaluation = useMemo(() => {
    if (!insp || !pack) return null;
    const responses = new Map(Object.entries(insp.responses || {}));
    const actionCodes = new Map((pack.vocabularies?.action_codes || []).map(a => [a.action_id, a]));
    return scoreInspection(pack.items || [], responses, insp.vessel || {}, { actionCodes });
  }, [insp, pack]);

  const findings = useMemo(() => {
    if (!insp || !pack || !evaluation) return [];
    const itemById = new Map((pack.items || []).map(i => [i.item_id, i]));
    const dcode = new Map((pack.vocabularies?.deficiency_codes || []).map(c => [c.code_id, c]));
    const acode = new Map((pack.vocabularies?.action_codes || []).map(a => [a.action_id, a]));
    return evaluation.deficiencies.map(d => {
      const item = itemById.get(d.item_id) || {};
      const r = insp.responses[d.item_id] || {};
      return {
        code: item.item_code,
        requirement: item.requirement_text,
        cite: item.convention_reference,
        deficiency: dcode.get(r.deficiency_code_id),
        action: acode.get(r.action_code_id),
        remark: r.remark,
      };
    });
  }, [insp, pack, evaluation]);

  if (!insp || !pack) return <div className="wrap center">Preparing receipt…</div>;

  const v = insp.vessel || {};
  const certs = Object.values(insp.certificates || {});
  const detainable = evaluation?.state === 'DETAINABLE';

  return (
    <div className="wrap page">
      <h1>Inspection receipt</h1>
      <p className="lede">
        Give this to the Master before leaving the vessel. It is the officer&rsquo;s copy,
        and it is provisional until the record reaches the Agency.
      </p>

      <div className="receipt-doc">
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', gap: 16 }}>
          <div>
            <div style={{ fontFamily: 'var(--display)', fontSize: 22, fontWeight: 700, letterSpacing: '.04em', textTransform: 'uppercase' }}>
              Vessel MARPOL Compliance Inspection
            </div>
            <div className="mono" style={{ fontSize: 12.5, color: 'var(--ink-2)' }}>
              {pack.template?.form_reference} &middot; Nigerian Maritime Administration and Safety Agency
            </div>
          </div>
          <span className="stamp">Provisional</span>
        </div>

        <div className="notice" style={{ marginTop: 16 }}>
          No MCI number has been allocated. The Agency allocates it when this record
          is received, and issues the definitive report to the vessel&rsquo;s agent.
        </div>

        <h3>Vessel</h3>
        <dl className="kv2">
          <dt>Name</dt><dd>{v.vessel_name || '—'}</dd>
          <dt>IMO</dt><dd>{v.imo_number || '—'}</dd>
          <dt>Type</dt><dd>{v.vessel_type || '—'}</dd>
          <dt>Gross tonnage</dt><dd>{v.grt ?? '—'}</dd>
          <dt>Case</dt><dd>{insp.case_reference || '—'}</dd>
          <dt>Date</dt><dd>{insp.inspection_date}</dd>
          <dt>Device record</dt><dd>{insp.local_id}</dd>
        </dl>

        <h3>Outcome</h3>
        <dl className="kv2">
          <dt>Items applicable</dt><dd>{evaluation?.applicableCount ?? 0}</dd>
          <dt>Items answered</dt><dd>{evaluation?.answeredCount ?? 0}</dd>
          <dt>Deficiencies</dt><dd>{findings.length}</dd>
          <dt>Provisional score</dt><dd>{evaluation?.score != null ? `${evaluation.score}%` : '—'}</dd>
          <dt>State</dt><dd>{evaluation?.state}</dd>
        </dl>
        {detainable && (
          <div className="notice bad" style={{ marginTop: 12 }}>
            <strong>Detainable deficiency recorded.</strong> A detainable finding governs
            the outcome regardless of the score. The Agency will act on it directly.
          </div>
        )}

        {certs.length > 0 && (
          <>
            <h3>Certificates sighted</h3>
            <div className="deflist">
              {certs.map(c => (
                <div className="d" key={c.certificate_type}>
                  <strong>{c.certificate_type}</strong>
                  {' — '}{c.sighted_state === 'YES' ? `valid until ${c.valid_until || 'not stated'}` : 'not sighted'}
                  {c.expiry_flag === 'EXPIRED' && <span className="badge expired" style={{ marginLeft: 8 }}>Expired</span>}
                </div>
              ))}
            </div>
          </>
        )}

        <h3>Deficiencies raised</h3>
        {findings.length === 0
          ? <p style={{ color: 'var(--ink-2)' }}>None. No non-conformance was recorded against any applicable item.</p>
          : (
            <div className="deflist">
              {findings.map((f, i) => (
                <div className="d" key={i}>
                  <span className="mono" style={{ color: 'var(--flag)' }}>{f.code}</span>{' '}
                  {f.requirement}
                  <div className="mono" style={{ fontSize: 12.5, color: 'var(--ink-2)', marginTop: 3 }}>
                    {f.cite}
                    {f.deficiency && ` · code ${f.deficiency.code}`}
                    {f.action && ` · action ${f.action.code}${f.action.is_detention ? ' (detainable)' : ''}`}
                  </div>
                  {f.remark && <div style={{ fontSize: 14, marginTop: 4 }}>{f.remark}</div>}
                </div>
              ))}
            </div>
          )}

        <h3>Signatures</h3>
        <div className="grid2">
          {(insp.signatories || []).map(s => (
            <div className="sigbox" key={s.signatory_role}>
              {s.signature_path && <img src={s.signature_path} alt="" />}
              <div style={{ borderTop: '1px solid var(--line)', marginTop: 6, paddingTop: 6, fontSize: 13.5 }}>
                <strong>{s.name}</strong>
                <div className="mono" style={{ fontSize: 11.5, color: 'var(--ink-2)' }}>
                  {s.signatory_role.replace(/_/g, ' ')}
                </div>
              </div>
            </div>
          ))}
        </div>

        <p className="mono" style={{ fontSize: 11.5, color: 'var(--ink-2)', marginTop: 20 }}>
          Provisional receipt generated on the inspecting device at{' '}
          {new Date(insp.updated_at).toLocaleString()}. This document supports
          inspection and record-keeping. It does not certify the vessel and carries
          no regulatory force.
        </p>
      </div>

      <div className="actions" style={{ marginTop: 18 }}>
        <button className="btn" onClick={() => window.print()}>Print or save as PDF</button>
        <button className="btn ghost" onClick={() => go('/queue')}>Back to queue</button>
      </div>
    </div>
  );
}
