'use strict';
const express = require('express');
const PDFDocument = require('pdfkit');
const { query } = require('../db');
const { ROLES, authenticate, authorise } = require('../auth');

const router = express.Router();

/**
 * DEFINITIVE MCI REPORT.
 *
 * Generated by the server, not the device, and only after supervisory
 * approval. Three things make that the right point:
 *
 *   1. The MCI number is a server-allocated sequence. Two offline devices
 *      cannot both allocate one without colliding, so the authoritative
 *      report cannot exist before synchronisation.
 *   2. The compliance state on this report is the SERVER'S re-evaluation
 *      against the current rule set, which may differ from the device's if
 *      the device carried a superseded instrument version.
 *   3. An unapproved inspection is a submission, not a finding. Issuing a
 *      definitive report before a supervisor has seen it would give it a
 *      standing it does not have.
 *
 * Until then the Master holds the provisional receipt issued on the device.
 */
router.post('/inspections/:id/report', authenticate,
  authorise(ROLES.SUPERVISOR, ROLES.ADMINISTRATOR),
  async (req, res, next) => {
    try {
      const data = await gather(req.params.id);
      if (!data) return res.status(404).json({ error: 'inspection not found' });
      if (!data.inspection.approved_at) {
        return res.status(409).json({
          error: 'inspection not approved',
          reason: 'AWAITING_APPROVAL',
          note: 'A definitive report is issued only after supervisory approval. The Master holds the provisional receipt until then.',
        });
      }
      const { rows } = await query(
        `INSERT INTO report (inspection_id, report_type, generated_by, export_payload)
         VALUES ($1,'MCI_REPORT',$2,$3) RETURNING report_id, generated_at`,
        [req.params.id, req.user.user_id, JSON.stringify(exportPayload(data))]);

      res.locals.auditEntity = 'report';
      res.locals.auditEntityId = rows[0].report_id;
      res.locals.auditAction = 'GENERATE';
      return res.status(201).json({ report_id: rows[0].report_id, generated_at: rows[0].generated_at,
        download: `/api/reports/${rows[0].report_id}.pdf` });
    } catch (e) { return next(e); }
  });

/** Stream the report as a PDF, built from stored data with nothing re-entered. */
router.get('/reports/:id.pdf', authenticate, async (req, res, next) => {
  try {
    const { rows } = await query(
      `SELECT r.*, i.inspection_id FROM report r
         JOIN inspection i ON i.inspection_id = r.inspection_id
        WHERE r.report_id = $1`, [req.params.id]);
    if (!rows.length) return res.status(404).json({ error: 'report not found' });
    const data = await gather(rows[0].inspection_id);

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition',
      `inline; filename="MCI-${data.inspection.mci_number}.pdf"`);
    render(new PDFDocument({ size: 'A4', margin: 46 }), data).pipe(res);
  } catch (e) { return next(e); }
});

/* ------------------------------------------------------------------ */

async function gather(inspectionId) {
  const { rows: ins } = await query(
    `SELECT i.*, c.case_reference, c.port, c.berth,
            v.imo_number, v.vessel_name, v.vessel_type, v.grt, v.flag_state
       FROM inspection i
       JOIN compliance_case c ON c.case_id = i.case_id
       JOIN vessel v ON v.vessel_id = c.vessel_id
      WHERE i.inspection_id = $1`, [inspectionId]);
  if (!ins.length) return null;

  const [defs, certs, decls, sigs, notes] = await Promise.all([
    query(`SELECT d.*, dc.code AS d_code, dc.description AS d_desc,
                  ac.code AS a_code, ac.description AS a_desc, ac.is_detention,
                  ci.item_code, ci.requirement_text, ci.convention_reference, r.remark
             FROM deficiency d
             JOIN deficiency_code dc ON dc.code_id = d.code_id
             JOIN action_code ac ON ac.action_id = d.action_id
             JOIN inspection_response r ON r.response_id = d.response_id
             JOIN checklist_item ci ON ci.item_id = r.item_id
            WHERE d.inspection_id = $1 ORDER BY ci.item_code`, [inspectionId]),
    query(`SELECT * FROM certificate WHERE inspection_id=$1 ORDER BY certificate_type`, [inspectionId]),
    query(`SELECT * FROM waste_declaration WHERE inspection_id=$1 ORDER BY annex_code`, [inspectionId]),
    query(`SELECT * FROM signatory WHERE document_type='INSPECTION' AND document_id=$1`, [inspectionId]),
    query(`SELECT w.*, r.variance_flag, r.variance_percent, r.received_quantity, r.declared_quantity
             FROM waste_collection_note w
             LEFT JOIN reconciliation r ON r.wcn_id = w.wcn_id
            WHERE w.inspection_id = $1`, [inspectionId]),
  ]);

  return { inspection: ins[0], deficiencies: defs.rows, certificates: certs.rows,
           declarations: decls.rows, signatories: sigs.rows, wasteNotes: notes.rows };
}

const exportPayload = d => ({
  mci_number: d.inspection.mci_number,
  imo_number: d.inspection.imo_number,
  inspection_date: d.inspection.inspection_date,
  port: d.inspection.port,
  compliance_state: d.inspection.compliance_state,
  compliance_score: d.inspection.compliance_score,
  deficiencies: d.deficiencies.map(x => ({
    code: x.d_code, action: x.a_code, detainable: x.is_detention, item: x.item_code,
  })),
  waste: d.wasteNotes.map(w => ({
    wcn_number: w.wcn_number, variance_flag: w.variance_flag, variance_percent: w.variance_percent,
  })),
});

function render(doc, d) {
  const i = d.inspection;
  const H = (t) => doc.moveDown(0.7).fontSize(11).fillColor('#008751').text(t.toUpperCase())
                      .moveTo(46, doc.y + 2).lineTo(549, doc.y + 2).strokeColor('#D6DEDC').stroke()
                      .moveDown(0.4).fillColor('#0E1A1F').fontSize(10);
  const kv = (k, v) => doc.fontSize(9.5).fillColor('#4A5B63').text(`${k}  `, { continued: true })
                          .fillColor('#0E1A1F').text(String(v ?? '—'));

  doc.fontSize(17).fillColor('#0A1E2D')
     .text('VESSEL MARPOL COMPLIANCE INSPECTION REPORT');
  doc.fontSize(9).fillColor('#4A5B63')
     .text('Nigerian Maritime Administration and Safety Agency  ·  NIMASA/MCR/2023');
  doc.moveDown(0.5).fontSize(14).fillColor('#0A1E2D').text(`MCI ${i.mci_number}`);

  H('Vessel and port call');
  kv('Vessel', i.vessel_name); kv('IMO number', i.imo_number);
  kv('Type', i.vessel_type); kv('Flag', i.flag_state); kv('Gross tonnage', i.grt);
  kv('Port', i.port); kv('Berth', i.berth);
  kv('Inspection date', i.inspection_date); kv('Case', i.case_reference);

  H('Outcome');
  kv('Compliance state', i.compliance_state);
  kv('Score', i.compliance_score != null ? `${i.compliance_score}%` : '—');
  kv('Deficiencies raised', d.deficiencies.length);
  if (i.compliance_state === 'DETAINABLE') {
    doc.moveDown(0.3).fontSize(10).fillColor('#B3261E')
       .text('A detainable deficiency was recorded. It governs the outcome regardless of the score.');
    doc.fillColor('#0E1A1F');
  }

  if (d.certificates.length) {
    H('Certificates');
    d.certificates.forEach(c => kv(c.certificate_type,
      c.sighted_state === 'YES'
        ? `valid until ${c.valid_until || 'not stated'}${c.expiry_flag === 'EXPIRED' ? '  — EXPIRED' : ''}`
        : 'not sighted'));
  }

  H('Deficiencies');
  if (!d.deficiencies.length) doc.fontSize(10).text('None recorded.');
  d.deficiencies.forEach(x => {
    doc.fontSize(10).fillColor('#0E1A1F').text(`${x.item_code}  ${x.requirement_text}`);
    doc.fontSize(8.5).fillColor('#4A5B63')
       .text(`${x.convention_reference || ''}  ·  code ${x.d_code}  ·  action ${x.a_code}${x.is_detention ? ' (detainable)' : ''}`);
    if (x.remark) doc.fontSize(9).fillColor('#0E1A1F').text(x.remark);
    doc.moveDown(0.35);
  });

  if (d.declarations.length) {
    H('Waste declared for landing');
    d.declarations.filter(w => w.to_be_landed).forEach(w =>
      kv(`Annex ${w.annex_code}`, `${w.declared_quantity ?? '—'} ${w.quantity_unit || ''} ${w.waste_type || ''}`));
  }

  if (d.wasteNotes.length) {
    H('Waste custody');
    d.wasteNotes.forEach(w => {
      kv(`Note ${w.wcn_number}`, `stage ${w.custody_stage}`);
      if (w.variance_flag) {
        kv('  Reconciliation', `declared ${w.declared_quantity ?? '—'} · received ${w.received_quantity ?? '—'} · ${w.variance_flag}${w.variance_percent != null ? ` (${w.variance_percent}%)` : ''}`);
      }
    });
  }

  H('Signatures');
  d.signatories.forEach(s => kv(s.signatory_role.replace(/_/g, ' '),
    `${s.name}  ·  ${new Date(s.signed_at).toLocaleString()}`));

  doc.moveDown(1).fontSize(8).fillColor('#4A5B63')
     .text(`Generated ${new Date().toLocaleString()} from stored inspection data. Approved ${i.approved_at ? new Date(i.approved_at).toLocaleString() : '—'}. This report supports inspection and record-keeping; it does not certify the vessel and carries no regulatory force.`,
       { width: 503 });

  doc.end();
  return doc;
}

module.exports = router;
